"""empty message

Revision ID: 4043f9a910d0
Revises: 841d05ed2f7a
Create Date: 2022-08-31 16:23:06.138592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4043f9a910d0'
down_revision = '841d05ed2f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Businesses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Stores', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Stores', 'Businesses', ['business_id'], ['id'])
    op.add_column('Users', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Users', 'Stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'store_id')
    op.drop_constraint(None, 'Stores', type_='foreignkey')
    op.drop_column('Stores', 'business_id')
    op.drop_table('Businesses')
    # ### end Alembic commands ###
