"""empty message

Revision ID: 335ba4ec0c29
Revises: e6058bf4b47a
Create Date: 2019-10-24 17:18:33.743776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335ba4ec0c29'
down_revision = 'e6058bf4b47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('timestamp', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'timestamp')
    op.drop_column('Users', 'role')
    # ### end Alembic commands ###
