"""empty message

Revision ID: e6058bf4b47a
Revises: 
Create Date: 2019-10-22 17:25:27.529432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6058bf4b47a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Items', ['name'])
    op.create_unique_constraint(None, 'Stores', ['name'])
    op.create_unique_constraint(None, 'Users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Stores', type_='unique')
    op.drop_constraint(None, 'Items', type_='unique')
    # ### end Alembic commands ###
